apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jungminlim
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jm_ops.git'
    targetRevision: HEAD
    path: app-of-apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - path: frontend
      repoURL: 'https://github.com/jungminii/jungmin-vue_crud_security.git'
    - path: backend
      repoURL: 'https://github.com/jungminii/jungmin-springboot_crud_security.git'
